name: action-genai-commentor
description: Generate code comments using AST insertion
inputs:
  model:
    description: The LLM model to use for generation.
    required: false
  instructions:
    description: Additional prompting instructions for the LLM.
    required: false
  dry_run:
    description: If true, the script will not modify files.
    required: false
    default: false
  mock:
    description: If true, the script will mock LLM results.
    required: false
    default: false
  judge:
    description: If true, the script will judge the generated docs.
    required: false
    default: false
  update_existing:
    description: Update existing docs.
    required: false
    default: false
  max_edits:
    description: Maximum number of new or updated comments total.
    required: false
    default: 50
  kinds:
    description: >-
      The kinds of entities to target for documentation generation.
            This is a comma-separated list of entity types, e.g. "module,type,function,property,variable".
    required: false
    default: module,type,function,property
  exports_only:
    description: If true, only generate docs for exported entities.
    required: false
    default: false
  max_context:
    description: Maximum number of tokens to build content of requests.
    required: false
    default: 6000
  files:
    description: Files to process, separated by semi columns (;).
      .ts,.mts,.tsx,.mtsx,.cts,.py,.cs
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: true
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
outputs:
  text:
    description: The generated text output.
branding:
  color: yellow
  icon: filter
runs:
  using: docker
  image: Dockerfile
