name: action-genai-commentor
description: Generate TypeScript function documentation using AST insertion
inputs:
  model:
    description: The model to use for generating comments.
  instructions:
    description: Additional prompting instructions for the LLM.
    required: false
  dry_run:
    description: If true, the script will not modify files.
    required: false
    default: false
  missing:
    description: Generate missing docs.
    required: false
    default: true
  update:
    description: Update existing docs.
    required: false
    default: false
  max_files:
    description: Maximum number of files to process.
    required: false
    default: 100
  max_updates:
    description: Maximum number of new or updated comments total.
    required: false
    default: 100
  flex_tokens:
    description: Maximum number of tokens to build content of requests.
    required: false
    default: 12000
  github_token:
    description: "GitHub token with `models: read` permission at least."
    required: true
  debug:
    description: Enable debug logging.
    required: false
branding:
  color: yellow
  icon: filter
runs:
  using: docker
  image: Dockerfile
