name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  models: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate missing documentation
        uses: ./
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue: ${{ github.event.issue.number }}
