name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  models: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate missing documentation
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit modified files
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --staged --quiet || git commit -m "[genai] continuous documentation update"
          git push
